from __future__ import annotations

import tempfile
import unittest
from pathlib import Path

from novarix_stock.database import StockDatabase, StockError
from novarix_stock.models import ProductDraft


class StockCoreTests(unittest.TestCase):
    def setUp(self) -> None:
        self.temp_dir = tempfile.TemporaryDirectory()
        self.db_path = Path(self.temp_dir.name) / "stock_test.db"
        self.database = StockDatabase(self.db_path)

    def tearDown(self) -> None:
        self.temp_dir.cleanup()

    def _draft(self, **changes: object) -> ProductDraft:
        values: dict[str, object] = {
            "sku": "NOV-001",
            "name": "Producto de prueba",
            "purchase_price_cents": 125050,
            "sale_price_cents": 199990,
            "minimum_stock": 3,
            "photo_path": "C:/imagenes/producto.jpg",
            "initial_stock": 5,
        }
        values.update(changes)
        return ProductDraft(**values)  # type: ignore[arg-type]

    def test_full_stock_flow_and_persistence(self) -> None:
        created = self.database.add_product(self._draft())
        self.assertEqual((created.stock_total, created.stock_current, created.sold), (5, 5, 0))

        entered = self.database.register_entry(created.id, 7)
        self.assertEqual((entered.stock_total, entered.stock_current, entered.sold), (12, 12, 0))

        sold = self.database.register_sale(created.id, 9)
        self.assertEqual((sold.stock_total, sold.stock_current, sold.sold), (12, 3, 9))
        self.assertTrue(sold.needs_restock)

        reopened_database = StockDatabase(self.db_path)
        persisted = reopened_database.get_product(created.id)
        self.assertEqual(persisted, sold)

        reopened_database.delete_product(created.id)
        self.assertEqual(reopened_database.list_products(), [])

        reopened_again = StockDatabase(self.db_path)
        self.assertEqual(reopened_again.list_products(), [])

    def test_edit_preserves_stock_counters(self) -> None:
        created = self.database.add_product(self._draft())
        self.database.register_sale(created.id, 2)
        updated = self.database.update_product(
            created.id,
            self._draft(sku="NOV-EDIT", name="Producto editado", minimum_stock=4),
        )
        self.assertEqual(updated.name, "Producto editado")
        self.assertEqual((updated.stock_total, updated.stock_current, updated.sold), (5, 3, 2))
        self.assertTrue(updated.needs_restock)

    def test_sale_cannot_exceed_available_stock(self) -> None:
        product = self.database.add_product(self._draft(initial_stock=2))
        with self.assertRaisesRegex(StockError, "Stock insuficiente"):
            self.database.register_sale(product.id, 3)
        unchanged = self.database.get_product(product.id)
        self.assertEqual((unchanged.stock_current, unchanged.sold), (2, 0))  # type: ignore[union-attr]

    def test_sku_is_optional_autogenerated_and_manual_sku_stays_unique(self) -> None:
        first = self.database.add_product(self._draft(sku="  ", name="Automático 1"))
        second = self.database.add_product(self._draft(sku="", name="Automático 2"))
        manual = self.database.add_product(self._draft(sku="MANUAL-001", name="Manual"))

        self.assertEqual(first.sku, "STK-0001")
        self.assertEqual(second.sku, "STK-0002")
        self.assertEqual(manual.sku, "MANUAL-001")

        with self.assertRaisesRegex(StockError, "Ya existe"):
            self.database.add_product(self._draft(sku="manual-001", name="Duplicado"))

    def test_generated_sku_continues_after_existing_number(self) -> None:
        self.database.add_product(self._draft(sku="stk-0007", name="Manual numerado"))
        generated = self.database.add_product(self._draft(sku="", name="Automático"))

        self.assertEqual(generated.sku, "STK-0008")

    def test_non_positive_movements_are_rejected(self) -> None:
        product = self.database.add_product(self._draft())
        with self.assertRaises(StockError):
            self.database.register_entry(product.id, 0)
        with self.assertRaises(StockError):
            self.database.register_sale(product.id, -1)


if __name__ == "__main__":
    unittest.main()
